### ISSUE TITLE
m4k2 - Reentrancy in `GoatPairV1::burn` if token is a non-standard ERC20

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-goat-trading-judging#52]
m4k2

high

# Reentrancy in `GoatPairV1::burn` if token is a non-standard ERC20

## Summary
A reentrancy is possible is the `GoatPairV1::burn` method.

## Vulnerability Detail

The `GoatPairV1::burn` method is susceptible to reentrancy if the token used to create the liquidity pool is an ERC777 or a non-standard ERC20 token. This vulnerability allows attackers to potentially break or steal funds from the contract.

Furthermore, the `nonReentrant` modifier, which prevents reentrancy, is not applied to the `burn` function. The absence of strict checks for ERC20 compliance in the codebase allows for the creation of liquidity pools with ERC777 or similar tokens, exacerbating this vulnerability.

Given the increasing prevalence of non-standard ERC20 tokens, mitigating this vulnerability is crucial.
## Proof of concept

The vulnerability arises from the lack of respect for Check-Effects-Interactions (CEI) and the absence of protection against reentrancy. A snippet of the vulnerable code is provided below:

## Code Snippet
[https://github.com/sherlock-audit/2024-03-goat-trading/blob/main/goat-trading/contracts/exchange/GoatV1Pair.sol#L191-L217](https://github.com/sherlock-audit/2024-03-goat-trading/blob/main/goat-trading/contracts/exchange/GoatV1Pair.sol#L191-L217)

The vulnerability key part:

```solidity

        // Transfer liquidity tokens to the user
        IERC20(_weth).safeTransfer(to, amountWeth);

        // Reentrancy possible here
        IERC20(_token).safeTransfer(to, amountToken);
        uint256 balanceEth = IERC20(_weth).balanceOf(address(this));
        uint256 balanceToken = IERC20(_token).balanceOf(address(this));

        _update(balanceEth, balanceToken, true);
```

As evident from the code snippet, the Check-Effects-Interactions (CEI) principle is not adhered to, and due to the absence of safeguards against reentrancy, it becomes feasible to reenter the deposit or swap functions following LP withdrawal, while the reserves remain unaltered.

## Tool used

Manual analysis

Foundry tests

## Recommendation

Two solutions are possible to mitigate this vulnerability:

1. Apply the `nonReentrant` modifier on the `burn` function:
```diff
- function burn(address to) external returns (uint256 amountWeth, uint256 amountToken) {
+ function burn(address to) external returns (uint256 amountWeth, uint256 amountToken) nonReentrant {
```

2. Transfer token at the end of execution:

```diff
- IERC20(_weth).safeTransfer(to, amountWeth);
- IERC20(_token).safeTransfer(to, amountToken);

// Transfer liquidity tokens to the user
+ uint256 balanceEth = IERC20(_weth).balanceOf(address(this)) - amountWeth;
+ uint256 balanceToken = IERC20(_token).balanceOf(address(this)) - amountToken;

- uint256 balanceEth = IERC20(_weth).balanceOf(address(this));
- uint256 balanceToken = IERC20(_token).balanceOf(address(this));

_update(balanceEth, balanceToken, true);

+ IERC20(_weth).safeTransfer(to, amountWeth);
+ IERC20(_token).safeTransfer(to, amountToken);
```

Implementing one or both of these mitigation strategies will enhance the security of the GoatPairV1 liquidity pool contract against reentrancy attacks.

**Comment by ABDuullahi** [comment]
Escalate 

According to the [readMe](https://audits.sherlock.xyz/contests/178), ERC777 is not supported
>Which ERC777 tokens do you expect will interact with the smart contracts?

>None.

**Comment by sherlock-admin2** [comment]
> Escalate 
> 
> According to the [readMe](https://audits.sherlock.xyz/contests/178), ERC777 is not supported
> >Which ERC777 tokens do you expect will interact with the smart contracts?
> 
> >None.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by sherlock-admin2** [comment]
> Escalate 
> 
> According to the [readMe](https://audits.sherlock.xyz/contests/178), ERC777 is not supported
> >Which ERC777 tokens do you expect will interact with the smart contracts?
> 
> >None.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by m4k2** [comment]
Any tokens are eligible for pool creation within the protocol, including ERC777 tokens, as they are often utilized through ERC20 interfaces due to ERC777's backward compatibility.

OpenZeppelin documentation confirms this interoperability: [link](https://docs.openzeppelin.com/contracts/3.x/erc777#what_if_i_already_use_erc20), stating that ERC777 tokens can be interacted with as if they were ERC20 tokens, while retaining additional functionalities such as send hooks.

Therefore, since it's impractical to prohibit the usage of ERC777 tokens, and their utilization introduces a reentrancy vulnerability that can potentially result in the misappropriation of other users' funds, it's imperative to acknowledge and address this vulnerability.

**Comment by sherlock-admin2** [comment]
> Escalate
> Any tokens are eligible for pool creation within the protocol, including ERC777 tokens, as they are often utilized through ERC20 interfaces due to ERC777's backward compatibility.
> 
> OpenZeppelin documentation confirms this interoperability: [link](https://docs.openzeppelin.com/contracts/3.x/erc777#what_if_i_already_use_erc20), stating that ERC777 tokens can be interacted with as if they were ERC20 tokens, while retaining additional functionalities such as send hooks.
> 
> Therefore, since it's impractical to prohibit the usage of ERC777 tokens, and their utilization introduces a reentrancy vulnerability that can potentially result in the misappropriation of other users' funds, it's imperative to acknowledge and address this vulnerability.

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by cvetanovv** [comment]
I want to bring some clarity to why I left them valid. The sponsor has written that it will not use `ERC777`, but this can be done with non-standard ERC20 tokens with a callback. 
In the readme section where it says if non-standard tokens are expected it is written: "Besides what was mentioned above (not concerned about blocklists, will use fee-on-transfer, not rebasing, etc.) we don't expect more, but would appreciate feedback if there are important ones that could cause big problems."

This could be interpreted ambiguously as invalid/valid due to: "but would appreciate feedback if there are important ones that could cause big problems". 

I mean, it's not like they just wrote that no such tokens are expected. In recent days Sherlock has introduced Low severity for just such occasions. And if this contest had started after that update then I would agree that this is a Low severity issue. 
Because the word "feedback" might mean that they want to know about a vulnerability but it doesn't qualify for the prize pool. But since it is before this update I left it valid.

**Comment by adamidarrha** [comment]
This issue, nor its duplicates, qualify as a valid HIGH issue. Instead, it falls into the medium/low category. Refering to Sherlock Docs criteria for a HIGH issue:
1. Definite loss of funds without (extensive) limitations of external conditions.
2. Inflicts serious non-material losses (doesn't include contract simply not working).

Here, the wardens didn't provide an impact assessment for the issue created; they merely stated that it breaks the CEI pattern. Without clearly demonstrating how this leads to a loss of funds or serious material loss, the issue cannot be awarded a HIGH severity rating.

**Comment by detectiveking123** [comment]
This issue should be invalid. The README explicitly says ERC777 is disallowed, so potentially conflicting parts of the README should not be considered.

**Comment by chiranz** [comment]
As I have specified before this should not be considered.

**Comment by Evert0x** [comment]
I believe the escalation should be rejected and issue should be invalidated.

ERC777 is explicitly disallowed. Besides that, the following language

> > **Do you expect to use any of the following tokens with non-standard behaviour with the smart contracts?**
> 
> Besides what was mentioned above (not concerned about blocklists, will use fee-on-transfer, not rebasing, etc.) we don't expect more, **but would appreciate feedback if there are important ones that could cause big problems.**

Doesn't explicitly state that tokens with callback mechanisms should be allowed. For that reason, I believe a fair judgment is to invalidate it.

**Comment by m4k2** [comment]
ERC777 cannot be prohibited under any circumstance, and it possesses the capability to mimic ERC20 functionality. 

Moreover, pools are established by users rather than protocol owners.
As a result, if a user opts to establish a malicious pool, the protocol lacks the means to prevent it, thereby magnifying the significance of this vulnerability.

Wishing you a pleasant day.

**Comment by Joshuajee** [comment]
Only the specified pool will be in danger, the protocol team can simply say that they don't support ERC777. Rebasing tokens also poses an issue, but the protocol doesn't plan to support them. Creating a pool with ERC777 is going against the protocol specs. I believe that, if someone goes against the specs of a protocol, they only have themselves to blame. Moreover, this issue is limited to the specified pool.

**Comment by m4k2** [comment]
You're correct; it's only restricted to specific pools. However, the malicious owner of ERC777 can manipulate the pool, leaving the users vulnerable instead of the pool creator. 

This could severely damage the protocol's reputation on social media platforms. Consequently, the protocol may lose the trust of its users.

**Comment by Joshuajee** [comment]
Still, it is the user's fault. The protocol doesn't support that particular type of token, there are many weird ERC20 behaviors. If I put a rebasing token on uniswap then I lose my funds. I am the one at fault.

**Comment by m4k2** [comment]
Furthermore, please remember that even if certain users possess the proficiency to comprehend Solidity (which constitutes only a very small percentage of users), and detect that  an ERC777 token obfuscate itself behind ERC20 interface, others will not.

Consequently, a significant portion of users may inadvertently fall victim to rug pulls.

**Comment by Evert0x** [comment]
Result:
Invalid
Has Duplicates

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ABDUullahi](https://github.com/sherlock-audit/2024-03-goat-trading-judging/issues/52/#issuecomment-2039232148): accepted
