### ISSUE TITLE
aycozynfada - Incorrect Fee Update Address in GoatV1Pair.burn when using removeLiquidityETH()

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-goat-trading-judging#80]
aycozynfada

high

# Incorrect Fee Update Address in GoatV1Pair.burn when using removeLiquidityETH()

https://github.com/sherlock-audit/2024-03-goat-trading/blob/main/goat-trading/contracts/periphery/GoatRouterV1.sol#L110-L146
https://github.com/sherlock-audit/2024-03-goat-trading/blob/main/goat-trading/contracts/exchange/GoatV1Pair.sol#L191-L217

## Summary
The burn function incorrectly updates the fee address in GoatV1Pair.burn when called by removeLiquidityETH() because the removeLiquidityETH() sets the to address as the GoatRouterV1.sol contract address 
## Vulnerability Detail
When removing liquidity as ETH, the removeLiquidityETH() is called, this functions doesn't call GoatV1Pair.burn but calls removeLiquidity() which is the function that eventually calls GoatV1Pair.burn.
The issue arises in the removeLiquidityETH() which sets the "TO" parameter to address.this before calling removeLiquidity(). 
removeLiquidity() calls GoatV1Pair.burn to remove liquidity and transfer ETH back to the GoatRouterV1 contract. Although the ETH is subsequently transferred to the intended recipient through removeLiquidityETH(), the intended recipient is denied fee rewards because GoatV1Pair.burn  updates fees rewards for GoatRouterV1 contract address and not the recipient address
## Impact
High as there is Incorrect Fee Distribution  and protocol  makes away with rewards intended for users, also anybody can GoatRouterV1.withDraw, input the router address and make away with fees recorded during this transactions
## Code Snippet
removeLiquidityETH() calls removeLiquidity below and uses address.this as "to address

```solidity
   function removeLiquidityETH(
        address token,
        uint256 liquidity,
        uint256 tokenMin,//users receives lesss token than expected for FET tokens 
        uint256 ethMin,//slippage is only checked in removeliquidity
        address to,
        uint256 deadline
    ) external ensure(deadline) returns (uint256 amountWeth, uint256 amountToken) {
        (amountWeth, amountToken) = removeLiquidity(token, liquidity, tokenMin, ethMin, address(this), deadline);
        IERC20(token).safeTransfer(to, amountToken);
        IWETH(WETH).withdraw(amountWeth);
        (bool success,) = to.call{value: amountWeth}("");
        if (!success) {
            revert GoatErrors.EthTransf erFailed();
        }
    }

    // **** REMOVE LIQUIDITY ****
    function removeLiquidity(
        address token,
        uint256 liquidity,
        uint256 tokenMin,
        uint256 wethMin,
        address to,
        uint256 deadline
    ) public nonReentrant ensure(deadline) returns (uint256 amountWeth, uint256 amountToken) {
        address pair = GoatV1Factory(FACTORY).getPool(token);

        IERC20(pair).safeTransferFrom(msg.sender, pair, liquidity);
        (amountWeth, amountToken) = GoatV1Pair(pair).burn(to);
        if (amountWeth < wethMin) {
            revert GoatErrors.InsufficientWethAmount();
        }
        if (amountToken < tokenMin) {
            revert GoatErrors.InsufficientTokenAmount();
        }
    }
```
Burn function updates fees to router instead of recipient address
```solidity
  function burn(address to) external returns (uint256 amountWeth, uint256 amountToken) {
        uint256 liquidity = balanceOf(address(this));

        // initial lp can bypass this check by using different
        // to address so _lastPoolTokenSender is used
        if (_vestingUntil == _MAX_UINT32) revert GoatErrors.PresalePeriod();

        uint256 totalSupply_ = totalSupply();
        amountWeth = (liquidity * _reserveEth) / totalSupply_;
        amountToken = (liquidity * _reserveToken) / totalSupply_;
        if (amountWeth == 0 || amountToken == 0) {
            revert GoatErrors.InsufficientLiquidityBurned();
        }

        _updateFeeRewards(to);
        _burn(address(this), liquidity);

        // Transfer liquidity tokens to the user
        IERC20(_weth).safeTransfer(to, amountWeth);
        IERC20(_token).safeTransfer(to, amountToken);
        uint256 balanceEth = IERC20(_weth).balanceOf(address(this));
        uint256 balanceToken = IERC20(_token).balanceOf(address(this));

        _update(balanceEth, balanceToken, true);

        emit Burn(msg.sender, amountWeth, amountToken, to);
    }

```
## Tool used

Manual Review

## Recommendation
add an input parameter that ensure the recipient address included when calling GoatV1Pair.burn from removeLiquidityETH()

**Comment by adamidarrha** [comment]
invalid issue, The warden misunderstands how fee distribution works in `removeLiquidityETH:GoatRouterV1`. The claim that the router receives fees from the liquidity provider calling this function is incorrect. Here's why:

- Fee accrual requires holding LP tokens: Fees accrue to LP token holders over time as swaps occur. Before any change in LP token balance (transfers, mint, or burn), the protocol updates the accrued fees for the affected holder.
- to address receives underlying tokens, not fees: The to address in `burn:GoatV1Pair` receives the underlying tokens from the burned LP tokens, not any accumulated fees.

Reasons why the issue is invalid:

1. Router doesn't hold LP tokens: The router transfers LP tokens directly to the pool, never holding them to accrue fees. Even if it did, accruing fees depends on holding, not merely receiving LP tokens.
2. _beforeTokenTransfer updates user's accrued fees: When the LP token transfer occurs, `_beforeTokenTransfer` executes, accruing fees to the user based on their balance before the transfer.

**scenario**
Step-by-step breakdown disproving the warden's claim:

1. User calls `removeLiquidityETH:GoatRouterV1`

```solidity=131
 function removeLiquidityETH(
        address token,
        uint256 liquidity,
        uint256 tokenMin,
        uint256 ethMin,
        address to,
        uint256 deadline
    ) external ensure(deadline) returns (uint256 amountWeth, uint256 amountToken) {
=>       (amountWeth, amountToken) = removeLiquidity(token, liquidity, tokenMin, ethMin, address(this), deadline);
```

2. `removeLiquidity` is called with `to=address(this)`

```solidity=111
function removeLiquidity(
        address token,
        uint256 liquidity,
        uint256 tokenMin,
        uint256 wethMin,
        address to,
        uint256 deadline
    ) public nonReentrant ensure(deadline) returns (uint256 amountWeth, uint256 amountToken) {
        address pair = GoatV1Factory(FACTORY).getPool(token);

=>        IERC20(pair).safeTransferFrom(msg.sender, pair, liquidity);
=>        (amountWeth, amountToken) = GoatV1Pair(pair).burn(to);
```

3. Router transfers LP tokens to the pair (never holds them) Line 121. burn:GoatV1Pair is called L122.

```solidity=191
    function burn(address to) external returns (uint256 amountWeth, uint256 amountToken) {
        uint256 liquidity = balanceOf(address(this));

        // initial lp can bypass this check by using different
        // to address so _lastPoolTokenSender is used
        if (_vestingUntil == _MAX_UINT32) revert GoatErrors.PresalePeriod();

        uint256 totalSupply_ = totalSupply();
        amountWeth = (liquidity * _reserveEth) / totalSupply_;
        amountToken = (liquidity * _reserveToken) / totalSupply_;
        if (amountWeth == 0 || amountToken == 0) {
            revert GoatErrors.InsufficientLiquidityBurned();
        }

=>       _updateFeeRewards(to);
```

4. `_updateFeeRewards(to=routerAddress)` is executed.

```solidity=933
    function _updateFeeRewards(address lp) internal {
        // save for multiple reads
        uint256 _feesPerTokenStored = feesPerTokenStored;
        lpFees[lp] = _earned(lp, _feesPerTokenStored);
        feesPerTokenPaid[lp] = _feesPerTokenStored;
    }
```

5. `_earned(lp=address(router))` calculates accrued router fees, which equal 0 due to a 0 LP token balance for the router.

```solidity=950
function _earned(address lp, uint256 _feesPerTokenStored) internal view returns (uint256) {
        uint256 feesPerToken = _feesPerTokenStored - feesPerTokenPaid[lp];
        uint256 feesAccrued = (balanceOf(lp) * feesPerToken) / 1e18;
        return lpFees[lp] + feesAccrued;
    }
```

the balanceOf(lp=address(router)) = 0 because like i said before it transfers to the pair and doesn't hold any. so the feesAccrued = 0. which means the router gets 0 fees for the burn.

6. `_beforeTokenTransfer` updates the user's accrued fees based on their balance before the transfer, so he never loses fees.

```solidity=921
_updateFeeRewards(from);
if (to != address(this)) {
    _updateFeeRewards(to);
}
```

**Proof Of Concept**

A Foundry POC demonstrates this:

1. LP adds liquidity.
2. Swaps are simulated to generate fees.
3. Initial fees owed to LP and router are checked.
4. LP calls removeLiquidityETH.
5. Post-transfer fees owed are checked. Assert the following:
6. LP's accrued fees remain the same.
7. Router's accrued fees are 0.
8. LP withdraws fees and receives the correct amount.
9. Router's withdraw attempt yields 0 fees.

paste this in test/foundry/exchange/GoatV1Pair.t.sol & run forge test --match-test  testRemoveLiquidityETH -vvvv

```solidity
function _setupPair() internal {

        GoatTypes.InitParams memory initParams;
        initParams.virtualEth = 10e18;
        initParams.initialEth = 10e18;
        initParams.initialTokenMatch = 1000e18;
        initParams.bootstrapEth = 10e18;
        uint256 wethAmount = 10e18;
        _mintInitialLiquidity(initParams, users.lp);

        wethAmount = _swapWethForTokens(
            wethAmount,
            100e18,
            users.alice,
            SwapRevertType.None
        );
        uint256 fees = (wethAmount * 99) / 10000;
        uint256 totalLpFees = (fees * 40) / 100;
        uint256 totalSupply = pair.totalSupply();
        uint256 feesPerTokenStored = (totalLpFees * 1e18) / totalSupply;
        uint256 lpBalance = pair.balanceOf(users.lp);
        uint256 lpFees = (feesPerTokenStored * lpBalance) / 1e18;

        feesPerTokenStored = pair.feesPerTokenStored();
        uint256 earned = pair.earned(users.lp);
    }

    function _setUpAddress(address user) internal returns (uint wethStart, uint tokenStart) {
        (uint256 wethR, uint256 tokenR) = pair.getReserves();
        wethStart = wethR+ 1e18 ;
        tokenStart= tokenR+ 100e18 ;

        vm.deal(user,wethStart);
        _fundMe(IERC20(goat), user, tokenStart );
        vm.prank(user);
        weth.deposit{value: wethStart}();
    }

    function testRemoveLiquidityETH() public {

        _setupPair();

        address normalUser = address(0x001);

        (uint wethStart, uint tokenStart) = _setUpAddress(normalUser);

        // normalUser adding Liquidity
        vm.startPrank(normalUser);
        weth.transfer(address(pair), wethStart - 1e18);
        goat.transfer(address(pair), tokenStart - 100e18);
        pair.mint(normalUser);
        vm.stopPrank();
        uint256 balancenormalUser = pair.balanceOf(normalUser);
        uint balanceWethnormalUser = weth.balanceOf(normalUser);

        // Wait until lock time is over
        vm.warp(pair.lockedUntil(normalUser) + 1);

        {//give user weth
        address swappingUser = address(0x002);

        uint256 wethSwap = 1e18;
        vm.deal(swappingUser, wethSwap);

        vm.startPrank(swappingUser);
        weth.deposit{value: wethSwap}();
        
        // simulate user swaps to add fees to protocol
        weth.transfer(address(pair), wethSwap);
        (uint wethReserveBefore, uint tokenReserveBefore) = pair.getReserves();
        uint amountTokenOut = GoatLibrary.getTokenAmountOutAmm(
            wethSwap,
            wethReserveBefore,
          tokenReserveBefore 
        );
        pair.swap(amountTokenOut, 0, swappingUser);
        vm.stopPrank();
        }

        //seeing how much fees are owed to the normalUser
        uint256 feesUnclaimedByNormalUser = pair.earned(normalUser);
        console.log("fees unclaimed by normalUser:", feesUnclaimedByNormalUser);

        //see how much fees are unclaimed by the router
        uint256 feesUnclaimedByRouter = pair.earned(address(router));
        console.log("fees unclaimed by the router:", feesUnclaimedByRouter);

        //normal user removes liquidity using removeLiquidityETH router function
        vm.startPrank(normalUser);

        pair.approve(address(router), balancenormalUser);

        router.removeLiquidityETH(
            address(goat),
            balancenormalUser,
            0,
            0,
            normalUser,
            block.timestamp + 1000
        );

        //assert that the normalUser still got his fees
        uint256 feesUnclaimedByNormalUserAfterRemovingLiquidity = pair.earned(normalUser);
        console.log("fees unclaimed by normalUser after removing liquidity:", feesUnclaimedByNormalUserAfterRemovingLiquidity);
        assert(feesUnclaimedByNormalUser == feesUnclaimedByNormalUserAfterRemovingLiquidity);

        //assert that the router got no fees
        uint256 feesUnclaimedByRouterAfterRemovingLiquidity = pair.earned(address(router));
        console.log("fees unclaimed by the router after removing liquidity:", feesUnclaimedByRouter);
        assert(feesUnclaimedByRouter == 0);

        //normal user withdraws fees after calling removing liquidity function
        pair.withdrawFees(normalUser);
        console.log("fee received by normalUser:", weth.balanceOf(normalUser) - balanceWethnormalUser);
        assert(weth.balanceOf(normalUser) == balanceWethnormalUser + feesUnclaimedByNormalUser);
        vm.stopPrank();

        //see that the router got no fees
        vm.startPrank(address(router));
        pair.withdrawFees(address(router));
        console.log("fee received by the router:", weth.balanceOf(address(router)));
        assert(weth.balanceOf(address(router)) == 0);
        vm.stopPrank();
    }
```

here is the output logs

```solidity
fees unclaimed by normalUser: 1980000000000000
fees unclaimed by the router: 0
fees unclaimed by normalUser after removing liquidity: 1980000000000000
fees unclaimed by the router after removing liquidity: 0
fee received by normalUser: 1980000000000000
fee received by the router: 0
```

this issue is invalidated.

**Comment by zzykxx** [comment]
Escalate

Invalid, check @adamidarrha comment

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Invalid, check @adamidarrha comment

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Aycozy** [comment]
I believe this issue is wrongly invalidated . And my claim that the router can receive fee rewards still stands because according to the title of this issue, the _updateFeeRewards() updates the address eligible for reward to the router's address when removeLiquidityETH is called by a User.  I believe this is furthermore a problem as the router can be eligible for liquidity pool rewards if a router is minted liquidity, where in such a case they hold Lp tokens and become a liquidity provider, this is proved by a POC a couple of steps below. 

The POC  provided by the other warden contains  crucial errors as it logs a variable "feesUnclaimedByRouter"  when asserting that user has no fees instead of logging the variable "feesUnclaimedByRouterAfterRemovingLiquidity"

```
  //This statement logs result for feesUnclaimedByRouter  which is also the previous result so nothing changes
        uint256 feesUnclaimedByRouterAfterRemovingLiquidity = pair.earned(address(router));
        console.log("fees unclaimed by the router after removing liquidity:", feesUnclaimedByRouter);
```
The other warden also prepares the POC in the test/foundry/exchange/GoatV1Pair.t.sol test suites, which is not the ideal environment as it erroneously inputs new variables apart from the original contract state in the sense that the GoatV1Router from which removeLiquidity() is called does not support the _beforeTokenTransfer() interface which is however present in the GoatV1pair contract. Because the GoatV1Router doesn't support the _beforeTokenTransfer() interface, fees are not updated for liquidity providers prior to be sent from the router, therefore they  are updated to the router contract address upon reaching the GoatV1pair.

Below shows a POC where the router address is minted LP tokens, which sets it up for LP fee  rewards

```solidity
function testRouterReceiveRewards() public {
        _addLiquidityEthAndConvertToAmm();
        GoatV1Pair pair = GoatV1Pair(factory.getPool(addLiqParams.token));

        uint256 lpTotalSupply = pair.totalSupply();
        //AT THIS POINT PRESALE IS ENDED
        addLiqParams = addLiquidityParams(false, false); // new params
        // mint tokens to lp
        token.mint(lp_1, 100e18);
        vm.deal(lp_1, 1e18);
        // Lp provides liqudity
        vm.startPrank(lp_1);
        token.approve(address(router), 100e18);
        addLiqParams.to = address(router); // change to lp
        (uint256 reserveEth, uint256 reserveToken) = pair.getReserves(); // get reserves before adding liquidity to check for Lp minted later

        (uint256 tokenAmtUsed, uint256 wethAmtUsed, uint256 liquidity) = router
            .addLiquidityETH{value: 1e18}(
            addLiqParams.token,
            addLiqParams.tokenDesired,
            addLiqParams.tokenMin,
            addLiqParams.wethMin,
            addLiqParams.to,
            addLiqParams.deadline,
            addLiqParams.initParams
        );
        vm.stopPrank();

        // checks
        assertEq(weth.balanceOf(address(pair)), 11e18); // 10e18 + 1e18
        uint256 optimalTokenAmt = (1e18 * 250e18) / 10e18; // calculate optimal token amount using current reserves
        assertEq(token.balanceOf(address(pair)), 250e18 + optimalTokenAmt);

        // check liquidity
        uint256 amtWeth = token.balanceOf(address(pair)) - 10e18; // balance - reserve
        uint256 amtToken = token.balanceOf(address(pair)) - 250e18; // balance - reserve

        uint256 expectedLiquidity = Math.min(
            (amtWeth * lpTotalSupply) / 10e18,
            (amtToken * lpTotalSupply) / 250e18
        );
        assertEq(pair.balanceOf(address(router)), expectedLiquidity);
        console2.log(
            "Lp token balance of router address",
            pair.balanceOf(address(router))
        );
```
This is the router balance after minting them LP tokens
```
Running 1 test for test/foundry/periphery/GoatV1Router.t.sol:GoatV1RouterTest
[PASS] testRouterReceiveRewards() (gas: 5079629)
Logs:
  Lp token balance of router address 5000000000000000000
```

In the remaining part of the POC, we simulate 3 scenarios each where a user address provides liquidity to the pool, swap is done by a different user to generate fees for the protocol and then removeLiquidityEth() is called by the liquidity provider,  after which a check is made to assess the address that receives rewards remediated by these actions. The result reveals the router accumulating X3  of that of the main 3 liquidity providers,
result 
```
Running 1 test for test/foundry/periphery/GoatV1Router.t.sol:GoatV1RouterTest
[PASS] testRouterReceiveRewards() (gas: 5079629)
Logs:
  Lp token balance of router address 5000000000000000000
  0x4f81992FCe2E1846dD528eC0102e6eE1f61ed3e2 pair address
  wethRemoved A
  wethRemoved B
  wethRemoved C
  fees earned by lp_2 3283664999999995
  fees earned by lp_3 3283664999999994
  fees earned by lp_4 3283664999999994
  fees earned by router 9850994999999985

Test result: ok. 1 passed; 0 failed; 0 skipped; finished in 11.93ms
 
Ran 1 test suites: 1 tests passed, 0 failed, 0 skipped (1 total tests)
```

Full POC
run this in  test/periphery/GoatV1Router.t.sol & run forge test --match-test testRouterReceiveRewards -vvv
```solidity
 function testRouterReceiveRewards() public {
        _addLiquidityEthAndConvertToAmm();
        GoatV1Pair pair = GoatV1Pair(factory.getPool(addLiqParams.token));

        uint256 lpTotalSupply = pair.totalSupply();
        //AT THIS POINT PRESALE IS ENDED
        addLiqParams = addLiquidityParams(false, false); // new params
        // mint tokens to lp
        token.mint(lp_1, 100e18);
        vm.deal(lp_1, 1e18);
        // Lp provides liqudity
        vm.startPrank(lp_1);
        token.approve(address(router), 100e18);
        addLiqParams.to = address(router); // change to lp
        (uint256 reserveEth, uint256 reserveToken) = pair.getReserves(); // get reserves before adding liquidity to check for Lp minted later

        (uint256 tokenAmtUsed, uint256 wethAmtUsed, uint256 liquidity) = router
            .addLiquidityETH{value: 1e18}(
            addLiqParams.token,
            addLiqParams.tokenDesired,
            addLiqParams.tokenMin,
            addLiqParams.wethMin,
            addLiqParams.to,
            addLiqParams.deadline,
            addLiqParams.initParams
        );
        vm.stopPrank();

        // checks
        assertEq(weth.balanceOf(address(pair)), 11e18); // 10e18 + 1e18
        uint256 optimalTokenAmt = (1e18 * 250e18) / 10e18; // calculate optimal token amount using current reserves
        assertEq(token.balanceOf(address(pair)), 250e18 + optimalTokenAmt);

        // check liquidity
        uint256 amtWeth = token.balanceOf(address(pair)) - 10e18; // balance - reserve
        uint256 amtToken = token.balanceOf(address(pair)) - 250e18; // balance - reserve

        uint256 expectedLiquidity = Math.min(
            (amtWeth * lpTotalSupply) / 10e18,
            (amtToken * lpTotalSupply) / 250e18
        );
        assertEq(pair.balanceOf(address(router)), expectedLiquidity);
        console2.log(
            "Lp token balance of router address",
            pair.balanceOf(address(router))
        );
        

        token.mint(lp_2, 100e18);
        vm.deal(lp_2, 1e18);
        // Lp provides liqudity
        vm.startPrank(lp_2);
        token.approve(address(router), 100e18);
        addLiqParams.to = lp_2; // change to lp
        (
            uint256 tokenAmtUsedA,
            uint256 wethAmtUsedA,
            uint256 liquidityA
        ) = router.addLiquidityETH{value: 1e18}(
                addLiqParams.token,
                addLiqParams.tokenDesired,
                addLiqParams.tokenMin,
                addLiqParams.wethMin,
                addLiqParams.to,
                addLiqParams.deadline,
                addLiqParams.initParams
            );
        vm.stopPrank();

     

        GoatV1Pair _pair = GoatV1Pair(factory.getPool(addLiqParams.token));
        console2.log((address(GoatV1Pair(_pair))), "pair address");

        uint256 wethRemovedA = testSwapTokenToWeth();
        removeLiquidity(lp_2, liquidityA);
        console2.log("wethRemoved A");

        token.mint(lp_3, 100e18);
        vm.deal(lp_3, 1e18);
        // Lp provides liqudity
        vm.startPrank(lp_3);
        token.approve(address(router), 100e18);
        addLiqParams.to = lp_3; // change to lp
        (
            uint256 tokenAmtUsedB,
            uint256 wethAmtUsedB,
            uint256 liquidityB
        ) = router.addLiquidityETH{value: 1e18}(
                addLiqParams.token,
                addLiqParams.tokenDesired,
                addLiqParams.tokenMin,
                addLiqParams.wethMin,
                lp_3,
                block.timestamp + 1000,
                addLiqParams.initParams
            );
        vm.stopPrank();

        uint256 wethRemovedB = testSwapTokenToWeth();
        removeLiquidity(lp_3, liquidityB);
        console2.log("wethRemoved B");

        // Lp provides liqudity
        token.mint(lp_4, 100e18);
        vm.deal(lp_4, 1e18);
        vm.startPrank(lp_4);
        token.approve(address(router), 100e18);
        addLiqParams.to = lp_4; // change to lp
        (
            uint256 tokenAmtUsedC,
            uint256 wethAmtUsedC,
            uint256 liquidityC
        ) = router.addLiquidityETH{value: 1e18}(
                addLiqParams.token,
                addLiqParams.tokenDesired,
                addLiqParams.tokenMin,
                addLiqParams.wethMin,
                lp_4,
                block.timestamp + 1000,
                addLiqParams.initParams
            );

        vm.stopPrank();

        uint256 wethRemovedC = testSwapTokenToWeth();
        removeLiquidity(lp_4, liquidityC);
        console2.log("wethRemoved C");
        console2.log("fees earned by lp_2", _pair.earned(lp_2));
        console2.log("fees earned by lp_3", _pair.earned(lp_3));
        console2.log("fees earned by lp_4", _pair.earned(lp_4));
        console2.log("fees earned by router", _pair.earned(address(router)));
        vm.stopPrank();
    }

    function testSwapTokenToWeth() public returns (uint256 wethOut) {
        GoatV1Pair _pair = GoatV1Pair(factory.getPool(addLiqParams.token));
        uint256 amountOut = _swapWethToToken();
 

        // Now swap token to weth
        vm.startPrank(swapper);
        token.approve(address(router), amountOut + amountOut);
        uint256 amountWethOut = router.swapExactTokensForWeth(
            amountOut, // amountIn
            0, // no slippage protection for now
            address(token),
            swapper,
            block.timestamp
        );
        vm.stopPrank();
        // console2.log(amountWethOut, "weth removed");
        return amountWethOut;
    }

    function removeLiquidity(address liqProv, uint256 _liquidityA) public {
        GoatV1Pair _pair = GoatV1Pair(factory.getPool(addLiqParams.token));

        vm.startPrank(liqProv);
        _pair.approve(address(router), _liquidityA);
        vm.warp(block.timestamp + 2 days);

        router.removeLiquidityETH(
            addLiqParams.token,
            _liquidityA,
            0,
            0,
            liqProv,
            block.timestamp + 1000
        );
    }
```

Issue incorrectly Invalidated!!

**Comment by RobertMCForster** [comment]
@Aycozy I'm having trouble determining the exact situation you're worried about here.

Is the problem that the router receives fees intended for users during normal function of the contract, or that the router receives fees if it's holding LP tokens? And if the latter, in what case would it be holding LP tokens and why is that a problem?

You've also seemed to mention it may be receiving more rewards than normal users for the amount of LP tokens it holds, but it looks like it only received 3x as much as users in your example because it was holding tokens for all 3 swaps rather than only for 1. Is there something I'm missing there?

**Comment by Aycozy** [comment]
@RobertMCForster @zzykxx 
My concern is about the  address which GoatV1Pair updates fee rewards for when removeLiquidityEth() is triggered, 
To shed more light on this I'll bring you up to speed with the sequence of events that occurs when removeLiquidityEth() is triggered.

A. After execution, removeLiquidityETH calls removeLiquidity() immediately to process the request inputting the router(address(this)) as primary receiver of the liquidity been sent from GoatV1Pair. This works as intended because this function eventually forwards the liquidity to the  intended recipient.
```solidity
 function removeLiquidityETH(
        address token,
        uint256 liquidity,
        uint256 tokenMin,//users receives lesss token than expected for FET tokens 
        uint256 ethMin,//slippage is only checked in removeliquidity
        address to,
        uint256 deadline
    ) external ensure(deadline) returns (uint256 amountWeth, uint256 amountToken) {
                                                                              //router address == address(this)
        (amountWeth, amountToken) = removeLiquidity(token, liquidity, tokenMin, ethMin, address(this), deadline);
        IERC20(token).safeTransfer(to, amountToken);
        IWETH(WETH).withdraw(amountWeth);
        (bool success,) = to.call{value: amountWeth}("");
        if (!success) {
            revert GoatErrors.EthTransf erFailed();
        }
    }
```
B. However because removeLiquidity() calls GoatV1Pair with the router address in place, the _updateFeeRewards(to) in GoatV1Pair updates fees for the router address and not for the liquidity provider.
```solidity
  function removeLiquidity(
        address token,
        uint256 liquidity,
        uint256 tokenMin,
        uint256 wethMin,
        address to,
        uint256 deadline
    )
        public
        nonReentrant
        ensure(deadline)
        returns (uint256 amountWeth, uint256 amountToken)
    {
        address pair = GoatV1Factory(FACTORY).getPool(token);

        IERC20(pair).safeTransferFrom(msg.sender, pair, liquidity);
                                                  //to == router address
        (amountWeth, amountToken) = GoatV1Pair(pair).burn(to);
        if (amountWeth < wethMin) {
            revert GoatErrors.InsufficientWethAmount();
        }
        if (amountToken < tokenMin) {
            revert GoatErrors.InsufficientTokenAmount();
        }
    }
```
C. Here is the burn function, which updates fee rewards for the router address with _updateFeeRewards(to) . The "to parameter" set to receive rewards through _updateFeeRewards() is the router address 
I stand to be corrected but I believe, _updateFeeRewards() shouldn't update fee rewards for the router address, but for the liquidity provider. But in this sequence fees are not updated for the liquidity provider, but for the router address
```solidity
   function burn(
        address to
    ) external returns (uint256 amountWeth, uint256 amountToken) {
        uint256 liquidity = balanceOf(address(this));

        // initial lp can bypass this check by using different
        // to address so _lastPoolTokenSender is used
        if (_vestingUntil == _MAX_UINT32) revert GoatErrors.PresalePeriod();

        uint256 totalSupply_ = totalSupply();
        amountWeth = (liquidity * _reserveEth) / totalSupply_;
        amountToken = (liquidity * _reserveToken) / totalSupply_;
        if (amountWeth == 0 || amountToken == 0) {
            revert GoatErrors.InsufficientLiquidityBurned();
        }
      // updates fees for the router address
        _updateFeeRewards(to);
        _burn(address(this), liquidity);

```
D.  
Implication: Liquidity providers removing liquidity through removeLiquidityETH are grieved of their liquid pool rewards because fees are not updated for them. When they call pair.withdraw, new fees are not received.

**Comment by RobertMCForster** [comment]
@Aycozy The fee rewards are immediately updated again to the user in _beforeTokenTransfer before the LP gains any rewards. Unless you can provide a PoC demonstrating that the router receives rewards when it is not holding tokens, this is an invalid issue.

**Comment by Aycozy** [comment]
@RobertMCForster @zzykxx @cvetanovv 

yes, _beforeTokenTransfer() does that well. Albeit I stand with my assertion that pool should not be updating fees for the router address and the implications of the router holding pool tokens should never be downplayed.

This can be exploited easily by a malicious actor who mints pool tokens for the router address.
Therefore whenever a user swaps with removeLiquidityETH, reward fees are updated for both  liquidity provider and router address.  
Malicious actor accrues fees on all swaps through removeLiquidityETH(), which means protocol serve double rewards when removeLiquidityETH() is used. 
Malicious actor can then withdraw fees accrued on every transaction by calling  GoatRouterV1.withdrawFees with router address.  which sends weth equivalent of fees to the router address.
Although weth might be stuck on router address, pool loses weth reserves.
I believe router receiving extra fee rewards  is proved by my POC above

**Comment by adamidarrha** [comment]
@Aycozy 
I believe you have a misunderstanding of how the `_updateFeeRewards` function and fee accrual work. Let me clarify:

- Fee Accrual: The number of times you call `_updateFeeRewards` between T1 and T2 doesn't affect your final fee amount. The protocol calculates fees based on the change in `feesPerTokenStored` from each user's `feesPerTokenPaid` mapping. This mapping tracks the `feesPerTokenStored` value from the last time `_updateFeeRewards` was called. so fees accrue based on how much `feesPerTokenStored` changes between calls, not on the number of calls itself.
- Router and LP Tokens: Any LP tokens mistakenly sent to the router are effectively lost. This does not harm the protocol. The original sender loses both the underlying tokens and associated potential fee accrual. 

so there is no loss of funds for the protocol nor harm to it's users , that's why it's invalid.

**Comment by Aycozy** [comment]
hello @adamidarrha 
Thank you for bringing me to speed with that, my concern now is that the router on account of holding liquid pool tokens(minted to router by a malicious actor in this case) seems to be earning more fee rewards than other liquidity providers.
Proved by my POC.    //code is in my first comment
```soldity
Running 1 test for test/foundry/periphery/GoatV1Router.t.sol:GoatV1RouterTest
[PASS] testRouterReceiveRewards() (gas: 5079629)
Logs:
  Lp token balance of router address 5000000000000000000
  0x4f81992FCe2E1846dD528eC0102e6eE1f61ed3e2 pair address
  wethRemoved A
  wethRemoved B
  wethRemoved C
  fees earned by lp_2 3283664999999995
  fees earned by lp_3 3283664999999994
  fees earned by lp_4 3283664999999994
  fees earned by router 9850994999999985

Test result: ok. 1 passed; 0 failed; 0 skipped; finished in 11.93ms
 
Ran 1 test suites: 1 tests passed, 0 failed, 0 skipped (1 total tests)
```

That is why I am of the of the opinion that a malicious actor can exploit that by withdrawing what  seem like extra fee rewards to deplete pool weth balance not minding personal loss.
But then based on your explanation, the router should not be receiving more rewards than others. How come the tests shows that the router gets more fees?

**Comment by adamidarrha** [comment]
Hello @Aycozy 
i think it's because they don't have the same amount of LPTokens, but anyhow you still didn't provide a clear scenario where the router is getting the fees of the user. that's why it should be invalidated.

**Comment by Aycozy** [comment]
Alright thank you for the explanations @adamidarrha 
Cheers to @RobertMCForster too for the analysis and the neat work put on the code base.

**Comment by cvetanovv** [comment]
I agree with @adamidarrha escalation. We can invalidated the issue.

**Comment by Evert0x** [comment]
Planning to accept escalation and invalidate issue

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [zzykxx](https://github.com/sherlock-audit/2024-03-goat-trading-judging/issues/80/#issuecomment-2041351230): accepted
